config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: {minimum: 3}
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email],params[:password])
      redirect_back_or_to(:users,notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index,:new,:create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
DOCTYPE

html
  head
    title SorceryTrial
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    #nav
      -if current_user
        = link_to "Edit Profile", edit_user_path(current_user.id)
        = link_to "Logout", :logout, method: :post
      -else
        = link_to "Register", new_user_path
        = link_to "Login", :login

    div
      p#notice = flash[:notice]
      p#alert = flash[:alert]

    == yield

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    = text_field_tag :email

  .field
    = label_tag :password
    = password_field_tag :password

  .actions
    = submit_tag "Login"

app/views/user_sessions/crate.html.slim
h1 UserSessions#crate
p Find me in app/views/user_sessions/crate.html.slim

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 Login

== render 'form'

= link_to 'Back', users_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path